//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SystemResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SystemResources", typeof(SystemResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجود بالفعل.
        /// </summary>
        public static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إلغاء الحجز.
        /// </summary>
        public static string CannotCancelReservation {
            get {
                return ResourceManager.GetString("CannotCancelReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد انتهى وقت العرض بالفعل.
        /// </summary>
        public static string EndedShowTime {
            get {
                return ResourceManager.GetString("EndedShowTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القاعة وصلت إلى الحد الأقصى لعدد المقاعد المسموح بها.
        /// </summary>
        public static string HallCapacityReached {
            get {
                return ResourceManager.GetString("HallCapacityReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيمة غير صالحة.
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقييم غير صالح.
        /// </summary>
        public static string InvalidRating {
            get {
                return ResourceManager.GetString("InvalidRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   التاريخ جب أن يكون أقل من أو يساوي تاريخ   اليوم.
        /// </summary>
        public static string LessThanOrEqualToToday {
            get {
                return ResourceManager.GetString("LessThanOrEqualToToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الاسم موجود بالفعل.
        /// </summary>
        public static string NameAlreadyExists {
            get {
                return ResourceManager.GetString("NameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الحقل غير موجود.
        /// </summary>
        public static string NotExist {
            get {
                return ResourceManager.GetString("NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكرسي غير موجود في تلك القاعة.
        /// </summary>
        public static string SeatNotFoundInHall {
            get {
                return ResourceManager.GetString("SeatNotFoundInHall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا المقعد محجوز بالفعل.
        /// </summary>
        public static string SeatReserved {
            get {
                return ResourceManager.GetString("SeatReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت العرض محجوز بالفعل.
        /// </summary>
        public static string ShowTimeOverlap {
            get {
                return ResourceManager.GetString("ShowTimeOverlap", resourceCulture);
            }
        }
    }
}
